data:
  target: datasets.data_module.BaseDataModule
  params:
    train_config: configs/datasets/neutron_traj_train.yaml
    val_config: configs/datasets/neutron_traj_val.yaml

model:
  config: configs/models/neutron_deg_guided.yaml
  resume: ~

lightning:
  seed: ~
  mode: fit
  matmul_precision: high

  trainer:
    accelerator: auto
    precision: 32
    devices: [0]
    strategy: auto
    max_steps: 100001
    val_check_interval: 20000
    check_val_every_n_epoch: ~
    log_every_n_steps: 50

  callbacks:
    - target: trainers.model_checkpoint.GuidedDegradationCheckpoint
      params:
        save_dir: "./checkpoints/neutron_guided_degradation/"
        save_interval: 10000
        save_last: False
        verbose: True

    - target: pytorch_lightning.callbacks.LearningRateMonitor
      params:
        logging_interval: "step"

    - target: pytorch_lightning.callbacks.TQDMProgressBar
      params:
        refresh_rate: 1

  loggers:
    - target: pytorch_lightning.loggers.TensorBoardLogger
      params:
        save_dir: ./logs/
        version: "neutron_deg_guided"
